meta_product_name: "Laure CdP - Portfolio"
meta_title: "Portfolio - Laure CdP : Coding underway"
meta_description: "Showcase of my works and projects"
meta_image: "cover.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards